package com.github.JohannesLipp.odrljava.model.odrl.leftoperand;

public enum LeftOperand {
    absolutePosition,
    absoluteSpatialPosition,
    absoluteTemporalPosition,
    absoluteSize,
    count,
    dateTime,
    delayPeriod,
    deliveryChannel,
    elapsedTime,
    event,
    fileFormat,
    industry,
    language,
    media,
    meteredTime,
    payAmount,
    percentage,
    product,
    purpose,
    recipient,
    relativePosition,
    relativeSpatialPosition,
    relativeTemporalPosition,
    relativeSize,
    resolution,
    spatial,
    spatialCoordinates,
    systemDevice ,
    timeInterval,
    unitOfCount,
    version,
    virtualLocation
}
